services:
  - type: web
    name: securechat-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://699e4acda23b87d9235fd0d7--gosth.netlify.app
      - key: SESSION_LINK_BASE_URL
        value: https://699e4acda23b87d9235fd0d7--gosth.netlify.app
      - key: SOCKET_PUBLIC_URL
        value: https://secureapp-0vkd.onrender.com
